openapi: 3.0.0
info:
    title: petstore
    version: 2.0.0
    license:
        name: MIT
servers:
    -
        url: 'http://petstore.swagger.io/v2'
paths:
    /pets:
        get:
            tags:
                - pets
            parameters:
                -
                    name: limit
                    description: How many items to return at one time (max 100)
                    schema:
                        format: int32
                        type: integer
                    in: query
                    required: false
            responses:
                '200':
                    $ref: '#/components/responses/Pets-Response'
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            operationId: listPets
            summary: List all pets
        post:
            tags:
                - pets
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Ok:
                                    value: '"1"'
                    description: Null response
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            operationId: createPets
            summary: Create a pet
    '/pets/{petId}':
        get:
            tags:
                - pets
            parameters:
                -
                    examples:
                        Dog:
                            value: 1
                    name: petId
                    description: The id of the pet to retrieve
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    $ref: '#/components/responses/Dog'
                default:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: unexpected error
            operationId: showPetById
            summary: Info for a specific pet
        parameters:
            -
                examples:
                    Dog:
                        value: 1
                name: petId
                schema:
                    type: integer
                in: path
                required: true
components:
    schemas:
        Pet:
            required:
                - id
                - name
            type: object
            properties:
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                tag:
                    type: string
                version:
                    type: integer
            example:
                id: 55
                name: some text
                tag: some text
                version: 2
        Pets:
            type: array
            items:
                $ref: '#/components/schemas/Pet'
            example:
                -
                    id: 44
                    name: some text
                    tag: some text
                    version: 2
                -
                    id: 67
                    name: some text
                    tag: some text
                    version: 2
        Error:
            required:
                - code
                - message
            type: object
            properties:
                code:
                    format: int32
                    type: integer
                message:
                    type: string
            example:
                code: 76
                message: some text
    responses:
        Pets-Response:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Pets'
                    examples:
                        Pets:
                            value:
                                -
                                    id: 1
                                    name: Dog
                                    tag: pet
                                    version: 2
                                -
                                    id: 2
                                    name: Cat
                                    tag: pet
                                    version: 2
            description: |-
                [
                  {
                    "id": 1,
                    "name":"Dog",
                    "tag": "pet",
                    "version": "2"
                  },
                  {
                    "id": 2,
                    "name":"Cat",
                    "tag": "pet",
                    "version": "2"
                  }
                ]
        Dog:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Pet'
                    examples:
                        Dog:
                            value:
                                id: 1
                                name: Dog
                                tag: pet
                                version: 2
            description: |-
                {
                  "id": 1,
                  "name":"Dog",
                  "tag": "pet",
                  "version": "2"
                }
        Cat:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Pet'
                    examples:
                        Cat:
                            value:
                                id: 2
                                name: Cat
                                tag: pet
                                version: 2
            description: |-
                {
                  "id": 2,
                  "name":"Cat",
                  "tag": "pet",
                  "version": "2"
                }
        Error:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        Error:
                            value:
                                code: 1
                                message: Internal Server Error
                                version: 2
            description: |-
                {
                    "code": 76,
                    "message": "some text",
                    "version": "2"
                }
